### ISSUE TITLE
Error when adding gitlab setup to a project

### ISSUE THREAD

**Issue by yusdirman** [brandedcrate/errbit_gitlab_plugin#10]
Errbit version: 0.8.0-dev
rails version : Rails 4.2.10
ruby version : ruby 2.3.0p0

What i did
1. added gem errbit_gitlab_plugin to UserGemfile
1. bundle install
1. run server
1. go to app/show -> edit ( http://myerrbit:3000/apps/[key]/edit)
1. click on gitlab icon
1. add url for our company gitlab web
1. add token
1. add project/project_name
1. submit

below error returned

# NoMethodError in AppsController#update
### undefined method `detect' for nil:NilClass
```ruby
# Extracted source (around line #32):

 # Allow the tracker to validate its own params
  def validate_tracker
    (tracker.errors || {}).each do |k, v|
      errors.add k, v
    end
  end

```

Rails.root: /home/user/errbit

Application Trace | Framework Trace | Full Trace
app/models/issue_tracker.rb:32:in `validate_tracker'
app/controllers/apps_controller.rb:67:in `update'

```ruby
Request
Parameters:

{"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"",
 "app"=>{"name"=>"",
 "repository_branch"=>"",
 "github_repo"=>"",
 "bitbucket_repo"=>"",
 "asset_host"=>"",
 "current_app_version"=>"",
 "notify_on_errs"=>"1",
 "use_site_fingerprinter"=>"1",
 "notice_fingerprinter_attributes"=>{"error_class"=>"1",
 "message"=>"1",
 "backtrace_lines"=>"-1",
 "component"=>"1",
 "action"=>"1",
 "environment_name"=>"1",
 "id"=>""},
 "notify_all_users"=>"1",
 "issue_tracker_attributes"=>{"type_tracker"=>"gitlab",
 "options"=>{"endpoint"=>"",
 "api_token"=>"",
 "path_with_namespace"=>""},
 "id"=>""},
 "notification_service_attributes"=>{"type"=>"NotificationServices::SlackService",
 "service_url"=>"https://hooks.slack.com/services/",
 "room_id"=>"",
 "id"=>""}},
 "commit"=>"Update App",
 "id"=>""}
```

hope someone will help me.. thank you

**Comment by stevecrozz** [comment]
Did you figure this out @yusdirman ?

**Comment by yusdirman** [comment]
not yet @stevecrozz , I closed this first to test with different version on errbit.. currently testing on v0.3.0.dev but still same error occurred.

should I reopen this issue ?

**Comment by stevecrozz** [comment]
I don't mind keeping it open if its still a problem, although I don't think I have the time to look at it. Maybe someone else will notice and help. In case anyone does see this, I'm also happy to transfer the ownership of this plugin to someone who has the time to maintain it.
